[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 13

[colors.primary]
background = '#181818'
foreground = '#eeeeee'

# Cursor colors
[colors.cursor]
text =   '#ffffff'
cursor = '#bbbbbb'

# Normal colors
[colors.normal]
black =   '#242424'
red =     '#d61b15'
green =   '#59a413'
yellow =  '#fdb40b'
blue =    '#053a8c'
magenta = '#e40038'
cyan =    '#2594e0'
white =   '#eeeeee'

# Bright colors
[colors.bright]
black =   '#4a4a4a'
red =     '#fb1b18'
green =   '#6ac118'
yellow =  '#fdc70e'
blue =    '#0855fe'
magenta = '#fb004f'
cyan =    '#3ea7fc'
white =   '#8c00eb'
